### ISSUE TITLE
Spieler kann keine Fische platzieren, es sind aber auch keine notwendig

### ISSUE THREAD

**Issue by ralpht42** [ralpht42/fische-versenken#53]
Spieler kann in der Bauphase (nachdem der Server alle Fische platziert hat) auf mysteriöser Art keine eigenen Fische platzieren, da bereits "alle Fische platziert wurden". Dadurch ist ein Starten der Spielphase möglich, auch wenn der Spieler keine versenkbaren Fische hat. Im Anschluss kann daher der Gegner keine Fische versenken.

Die Ursache ist unbekannt, Lösung ebenfalls

![image](https://github.com/ralpht42/fische-versenken/assets/24992261/d1c23559-8793-4d90-9cf4-27f55c22616c)

**Comment by QHochgrebe** [comment]
Ich habe nun versucht, dass der Server zuerst seine Fische platziert.
Dann mache ich ihn auf ready und versuch dann den Client ready zu setzen.
Dann bekomme ich beim Client die Meldung, dass nicht alle Fische gesetzt wurden.

Bis jetzt konnte ich den Fehler nicht reproduzieren.
